package com.example.android.saiapp3;

import android.content.Intent;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {

    DataBaseHelper myDb;
    EditText txtName, txtSurName, txtMarks, txtId;
    Button btnClick, btnClick2, btnClick3;
    TextView txtResult;
    Intent intent, i;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        myDb = new DataBaseHelper(this);

        txtName = (EditText) findViewById(R.id.idName);
        txtSurName = (EditText) findViewById(R.id.idSurname);
        txtMarks = (EditText) findViewById(R.id.idMarks);
        txtId = (EditText) findViewById(R.id.idID);

        btnClick = (Button)findViewById(R.id.idBtn);
        btnClick2 = (Button)findViewById(R.id.idBtn2);
        btnClick3 = (Button)findViewById(R.id.idBtn3);

        txtResult = (TextView)findViewById(R.id.idResult);

        btnClick.setOnClickListener(new View.OnClickListener(){
           public void onClick(View v){

               ClickMe();
           }
        });

        btnClick2.setOnClickListener(new View.OnClickListener(){
            public void onClick(View v)
            {
                ClickMe2();
            }
        });

        btnClick3.setOnClickListener(new View.OnClickListener(){
            public void onClick(View v){

                ClickMe3();
            }
        });
    }

    private void ClickMe(){

        String name = txtName.getText().toString();
        String surname = txtSurName.getText().toString();
        String marks = txtMarks.getText().toString();

        if(name!= null && surname!=null && marks!=null ) {
            boolean result = myDb.insertData(name, surname, marks);

            if (result == true) {
                Toast.makeText(this, "1 Data Inserted Successfully", Toast.LENGTH_SHORT).show();
            } else {
                Toast.makeText(this, "2 Data Inserted Failed", Toast.LENGTH_SHORT).show();
            }
        }

        //Automatic Email Generation-(Android Implicit Intent)
        i = new Intent(Intent.ACTION_SEND);
        i.setData(Uri.parse("mailto:"));
        String[] s = {"hanutsingh5@gmail.com"};
        i.putExtra(Intent.EXTRA_EMAIL,s);
        i.putExtra(Intent.EXTRA_SUBJECT,"This is an autogenerated email");
        i.putExtra(Intent.EXTRA_TEXT,"This is an insertion in database:" + "\n" + "Name:-" + name + "\n" + "SurName:-" + surname + "\n" + "Marks:-" + marks);
        i.setType("message/rfc822");
        Intent chooser = Intent.createChooser(i,"Send Email");
        startActivity(chooser);


    }

    private void ClickMe2(){
        String id = txtId.getText().toString();
        int result = myDb.deleteData(id);
           Toast.makeText(this,result+" :Rows Affected/Data Deleted",Toast.LENGTH_SHORT).show();

        Intent intent = new Intent(Intent.ACTION_SENDTO, Uri.fromParts(
                "mailto", "", null));
/*
        //Automatic Email Generation-(Android Implicit Intent)
        i = new Intent(Intent.ACTION_SEND);
        i.setData(Uri.parse("email"));
        String[] s = {"hanutsingh5@gmail.com"};
        i.putExtra(Intent.EXTRA_EMAIL,s);
        i.putExtra(Intent.EXTRA_SUBJECT,"This is an autogenerated email");
        i.putExtra(Intent.EXTRA_TEXT,"This is a deletion from database:" + "\n" + "ID:-" + id);
        i.setType("message/rfc822");
        Intent chooser = Intent.createChooser(i,"Launch Email");
        startActivity(chooser);
*/
    }

    private void ClickMe3(){

        Cursor res = myDb.getAllData();
        StringBuffer stringBuffer = new StringBuffer();
        if (res!= null && res.getCount()>0)
        {
            while (res.moveToNext())
            {
                stringBuffer.append("Id: " + res.getString(0) + "\t\t\t");
                stringBuffer.append("Name: " + res.getString(1) + "\t\t\t");
                stringBuffer.append("SurName: " + res.getString(2) + "\t\t\t");
                stringBuffer.append("Marks: " + res.getString(3) + "\n");
            }
            txtResult.setText(stringBuffer.toString());
            Toast.makeText(this,"Data Accessed",Toast.LENGTH_SHORT).show();

        }
        else{
            Toast.makeText(this,"NO Data Accessed",Toast.LENGTH_SHORT).show();
        }

/*
        //Automatic Email Generation-(Android Implicit Intent)
        i = new Intent(Intent.ACTION_SEND);
        i.setData(Uri.parse("email"));
        String[] s = {"hanutsingh5@gmail.com"};
        i.putExtra(Intent.EXTRA_EMAIL,s);
        i.putExtra(Intent.EXTRA_SUBJECT,"This is an autogenerated email");

        i.putExtra(Intent.EXTRA_TEXT,"This is a Show in database:" + "\n" +
         while (res.moveToNext())
        {
            stringBuffer.append("Id: " + res.getString(0) + "\t\t\t");
            stringBuffer.append("Name: " + res.getString(1) + "\t\t\t");
            stringBuffer.append("SurName: " + res.getString(2) + "\t\t\t");
            stringBuffer.append("Marks: " + res.getString(3) + "\n");
        }
        );

        i.setType("message/rfc822");
        Intent chooser = Intent.createChooser(i,"Launch Email");
        startActivity(chooser);
*/
/*
        intent = new Intent(MainActivity.this,DetailsActivity.class);
        startActivity(intent);
*/

    }


    public void broadcastIntent(View view){
        Intent intent = new Intent();
        intent.setAction("android.intent.action.CUSTOM_INTENT");
        sendBroadcast(intent);
    }



}
