package com.example.android.saiapp3;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.widget.Toast;

public class MyReceiver extends BroadcastReceiver{
    Intent i;
    @Override
    public void onReceive(Context context, Intent intent) {
        Toast.makeText(context, "Intent Detected.", Toast.LENGTH_LONG).show();

        i = new Intent(Intent.ACTION_SEND);
        i.setData(Uri.parse("email"));
        String[] s = {"hanutsingh5@gmail.com"};
        i.putExtra(Intent.EXTRA_EMAIL,s);
        i.putExtra(Intent.EXTRA_SUBJECT,"This is an autogenerated email");
        i.putExtra(Intent.EXTRA_TEXT,"This is an insertion in database:");
        i.setType("message/rfc822");
        Intent chooser = Intent.createChooser(i,"Launch Email");

    }
}

